version: '3.7'
services:
  sender:
    build: .
    network_mode: host #host network to make network debugging with wireshark a bit easier
    environment:
      - SRT_TARGET=srt://IP:PORT
    volumes:
      - ./stats:/stats